# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecLoc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.4'
pod 'AWSRekognition'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'TagListView', '~> 1.0'

  # Pods for RecLoc

  target 'RecLocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecLocUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
